version: '3.9'
services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    x-develop:
      watch:
      - path: ./go.mod
        action: rebuild
      - path: ./main.go
        action: rebuild
      - path: ./static/
        action: sync
        target: /app/static/

